import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { format } from 'date-fns'

const COLORS = {
  navy: [30, 58, 138],
  ember: [234, 88, 12],
  slate: [100, 116, 139],
  light: [248, 249, 252],
  border: [219, 234, 254],
}

function drawHeader(doc, docType, docNumber) {
  // Navy header bar
  doc.setFillColor(...COLORS.navy)
  doc.rect(0, 0, 210, 32, 'F')

  // The Shield logo (simplified for PDF)
  doc.setFillColor(...COLORS.navy)
  doc.setDrawColor(...COLORS.ember)
  doc.setLineWidth(0.8)
  const shieldX = 16, shieldY = 8
  // Shield outline
  doc.lines(
    [[12, 0], [0, 10], [-6, 8], [-6, -8], [0, -10]],
    shieldX - 6, shieldY,
    [1, 1],
    'FD'
  )
  // Chevrons (white)
  doc.setDrawColor(255, 255, 255)
  doc.setLineWidth(0.6)
  doc.lines([[3, -2], [3, 2]], shieldX - 3, shieldY + 6)
  doc.lines([[3, -2], [3, 2]], shieldX - 3, shieldY + 10)
  doc.lines([[3, -2], [3, 2]], shieldX - 3, shieldY + 14)

  // Company name
  doc.setTextColor(255, 255, 255)
  doc.setFont('times', 'normal')
  doc.setFontSize(16)
  doc.text('GENESIS AIR SYSTEMS', 30, 14)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(191, 219, 254)
  doc.text('Heating · Cooling · Service', 30, 19)

  // Document type and number (right side)
  doc.setTextColor(255, 255, 255)
  doc.setFont('times', 'normal')
  doc.setFontSize(20)
  doc.text(docType.toUpperCase(), 194, 16, { align: 'right' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(253, 186, 116)
  doc.text(docNumber, 194, 22, { align: 'right' })
}

function drawCustomerBlock(doc, customer, address, yStart) {
  doc.setFontSize(8)
  doc.setTextColor(...COLORS.slate)
  doc.text('BILL TO', 16, yStart)

  doc.setFontSize(11)
  doc.setTextColor(...COLORS.navy)
  doc.setFont('helvetica', 'bold')
  doc.text(customer.name || '', 16, yStart + 5)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...COLORS.slate)
  let line = yStart + 10
  if (customer.contact) {
    doc.text(`Attn: ${customer.contact}`, 16, line)
    line += 4
  }
  if (address?.line1) {
    doc.text(address.line1, 16, line)
    line += 4
  }
  if (address?.line2) {
    doc.text(address.line2, 16, line)
    line += 4
  }
  if (address?.city || address?.state) {
    doc.text(`${address.city || ''}${address.city && address.state ? ', ' : ''}${address.state || ''} ${address.zip || ''}`.trim(), 16, line)
    line += 4
  }
  if (customer.email) {
    doc.text(customer.email, 16, line)
    line += 4
  }
  if (customer.phone) {
    doc.text(customer.phone, 16, line)
  }
}

function drawMetadata(doc, items, yStart) {
  let y = yStart
  items.forEach(({ label, value }) => {
    doc.setFontSize(8)
    doc.setTextColor(...COLORS.slate)
    doc.text(label.toUpperCase(), 130, y)

    doc.setFontSize(10)
    doc.setTextColor(...COLORS.navy)
    doc.setFont('helvetica', 'bold')
    doc.text(value || '—', 194, y, { align: 'right' })
    doc.setFont('helvetica', 'normal')
    y += 6
  })
}

function drawFooter(doc) {
  const pageHeight = doc.internal.pageSize.getHeight()
  doc.setDrawColor(...COLORS.border)
  doc.setLineWidth(0.3)
  doc.line(16, pageHeight - 18, 194, pageHeight - 18)

  doc.setFontSize(8)
  doc.setTextColor(...COLORS.slate)
  doc.text('Genesis Air Systems · Heating · Cooling · Service', 16, pageHeight - 12)
  doc.text('Thank you for your business', 194, pageHeight - 12, { align: 'right' })

  doc.setFontSize(7)
  doc.setTextColor(160, 174, 192)
  doc.text('Generated by Genesis Air Systems FSM · Powered by Midpoint', 105, pageHeight - 7, { align: 'center' })
}

export function generateEstimatePDF(estimate, lineItems, customer) {
  const doc = new jsPDF('p', 'mm', 'a4')

  drawHeader(doc, 'Estimate', estimate.estimate_number)

  drawCustomerBlock(doc, {
    name: customer.customer_type === 'commercial' ? customer.company_name : `${customer.first_name} ${customer.last_name}`,
    contact: customer.customer_type === 'commercial' ? customer.contact_name : null,
    email: customer.email,
    phone: customer.phone,
  }, {
    line1: customer.address_line1,
    line2: customer.address_line2,
    city: customer.city,
    state: customer.state,
    zip: customer.zip_code,
  }, 44)

  drawMetadata(doc, [
    { label: 'Estimate Date', value: estimate.created_at ? format(new Date(estimate.created_at), 'MMM d, yyyy') : null },
    { label: 'Valid Until', value: estimate.valid_until ? format(new Date(estimate.valid_until), 'MMM d, yyyy') : null },
    { label: 'Status', value: estimate.status?.toUpperCase() },
  ], 44)

  const tableData = (lineItems || []).map(item => [
    item.description || '',
    Number(item.quantity).toFixed(2),
    `$${Number(item.unit_price).toFixed(2)}`,
    item.is_taxable ? '✓' : '',
    `$${(Number(item.quantity) * Number(item.unit_price)).toFixed(2)}`,
  ])

  autoTable(doc, {
    startY: 90,
    head: [['Description', 'Qty', 'Unit Price', 'Tax', 'Total']],
    body: tableData,
    headStyles: {
      fillColor: COLORS.navy,
      textColor: [255, 255, 255],
      fontSize: 9,
      fontStyle: 'bold',
      cellPadding: 3,
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [30, 41, 59],
      cellPadding: 3,
    },
    alternateRowStyles: { fillColor: COLORS.light },
    columnStyles: {
      0: { cellWidth: 90 },
      1: { cellWidth: 18, halign: 'right' },
      2: { cellWidth: 30, halign: 'right' },
      3: { cellWidth: 15, halign: 'center' },
      4: { cellWidth: 25, halign: 'right' },
    },
    margin: { left: 16, right: 16 },
  })

  let finalY = doc.lastAutoTable.finalY + 6
  drawTotals(doc, estimate, finalY)

  if (estimate.notes) {
    doc.setFontSize(8)
    doc.setTextColor(...COLORS.slate)
    doc.text('NOTES', 16, finalY + 50)
    doc.setFontSize(9)
    doc.setTextColor(60, 73, 94)
    const noteLines = doc.splitTextToSize(estimate.notes, 100)
    doc.text(noteLines, 16, finalY + 55)
  }

  if (estimate.terms) {
    const startY = estimate.notes ? finalY + 80 : finalY + 50
    doc.setFontSize(8)
    doc.setTextColor(...COLORS.slate)
    doc.text('TERMS & CONDITIONS', 16, startY)
    doc.setFontSize(8)
    doc.setTextColor(60, 73, 94)
    const termsLines = doc.splitTextToSize(estimate.terms, 178)
    doc.text(termsLines, 16, startY + 5)
  }

  drawFooter(doc)

  doc.save(`Estimate-${estimate.estimate_number}.pdf`)
}

export function generateInvoicePDF(invoice, lineItems, customer) {
  const doc = new jsPDF('p', 'mm', 'a4')

  drawHeader(doc, 'Invoice', invoice.invoice_number)

  drawCustomerBlock(doc, {
    name: customer.customer_type === 'commercial' ? customer.company_name : `${customer.first_name} ${customer.last_name}`,
    contact: customer.customer_type === 'commercial' ? customer.contact_name : null,
    email: customer.email,
    phone: customer.phone,
  }, {
    line1: customer.address_line1,
    line2: customer.address_line2,
    city: customer.city,
    state: customer.state,
    zip: customer.zip_code,
  }, 44)

  drawMetadata(doc, [
    { label: 'Invoice Date', value: invoice.issued_at ? format(new Date(invoice.issued_at), 'MMM d, yyyy') : (invoice.created_at ? format(new Date(invoice.created_at), 'MMM d, yyyy') : null) },
    { label: 'Due Date', value: invoice.due_date ? format(new Date(invoice.due_date), 'MMM d, yyyy') : null },
    { label: 'Terms', value: invoice.payment_terms || 'Net 30' },
    { label: 'Status', value: invoice.status?.toUpperCase() },
  ], 44)

  const tableData = (lineItems || []).map(item => [
    item.description || '',
    Number(item.quantity).toFixed(2),
    `$${Number(item.unit_price).toFixed(2)}`,
    item.is_taxable ? '✓' : '',
    `$${(Number(item.quantity) * Number(item.unit_price)).toFixed(2)}`,
  ])

  autoTable(doc, {
    startY: 95,
    head: [['Description', 'Qty', 'Unit Price', 'Tax', 'Total']],
    body: tableData,
    headStyles: { fillColor: COLORS.navy, textColor: [255, 255, 255], fontSize: 9, fontStyle: 'bold', cellPadding: 3 },
    bodyStyles: { fontSize: 9, textColor: [30, 41, 59], cellPadding: 3 },
    alternateRowStyles: { fillColor: COLORS.light },
    columnStyles: {
      0: { cellWidth: 90 },
      1: { cellWidth: 18, halign: 'right' },
      2: { cellWidth: 30, halign: 'right' },
      3: { cellWidth: 15, halign: 'center' },
      4: { cellWidth: 25, halign: 'right' },
    },
    margin: { left: 16, right: 16 },
  })

  let finalY = doc.lastAutoTable.finalY + 6
  drawTotals(doc, invoice, finalY, true)

  if (invoice.notes) {
    doc.setFontSize(8)
    doc.setTextColor(...COLORS.slate)
    doc.text('NOTES', 16, finalY + 55)
    doc.setFontSize(9)
    doc.setTextColor(60, 73, 94)
    const noteLines = doc.splitTextToSize(invoice.notes, 100)
    doc.text(noteLines, 16, finalY + 60)
  }

  // Payment instructions box (only on invoices)
  doc.setFillColor(255, 247, 237)
  doc.setDrawColor(...COLORS.ember)
  doc.setLineWidth(0.3)
  doc.rect(16, finalY + 30, 178, 18, 'FD')
  doc.setFontSize(8)
  doc.setTextColor(...COLORS.ember)
  doc.setFont('helvetica', 'bold')
  doc.text('PAYMENT INSTRUCTIONS', 20, finalY + 36)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...COLORS.navy)
  doc.text(`Please remit payment by ${invoice.due_date ? format(new Date(invoice.due_date), 'MMMM d, yyyy') : 'the due date above'}. For questions, contact Genesis Air Systems.`, 20, finalY + 42)

  drawFooter(doc)

  doc.save(`Invoice-${invoice.invoice_number}.pdf`)
}

function drawTotals(doc, record, yStart, isInvoice = false) {
  const x = 140
  let y = yStart

  doc.setFontSize(9)
  doc.setTextColor(...COLORS.slate)
  doc.text('Subtotal', x, y)
  doc.setTextColor(...COLORS.navy)
  doc.text(`$${Number(record.subtotal || 0).toFixed(2)}`, 194, y, { align: 'right' })
  y += 5

  if (Number(record.discount_amount) > 0) {
    doc.setTextColor(...COLORS.slate)
    doc.text('Discount', x, y)
    doc.setTextColor(...COLORS.navy)
    doc.text(`-$${Number(record.discount_amount).toFixed(2)}`, 194, y, { align: 'right' })
    y += 5
  }

  if (Number(record.tax_rate) > 0) {
    doc.setTextColor(...COLORS.slate)
    doc.text(`Tax (${(Number(record.tax_rate) * 100).toFixed(3)}%)`, x, y)
    doc.setTextColor(...COLORS.navy)
    doc.text(`$${Number(record.tax_amount || 0).toFixed(2)}`, 194, y, { align: 'right' })
    y += 5
  }

  // Total line
  doc.setDrawColor(...COLORS.navy)
  doc.setLineWidth(0.5)
  doc.line(x, y + 1, 194, y + 1)
  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(...COLORS.navy)
  doc.text(isInvoice ? 'AMOUNT DUE' : 'TOTAL', x, y)
  doc.setTextColor(...COLORS.ember)
  doc.text(`$${Number(record.total_amount || 0).toFixed(2)}`, 194, y, { align: 'right' })
  doc.setFont('helvetica', 'normal')

  if (isInvoice && Number(record.amount_paid) > 0) {
    y += 5
    doc.setFontSize(9)
    doc.setTextColor(...COLORS.slate)
    doc.text('Paid', x, y)
    doc.setTextColor([16, 185, 129])
    doc.text(`$${Number(record.amount_paid).toFixed(2)}`, 194, y, { align: 'right' })
  }
}
